pull_request_rules:
  - name: forge approval
    conditions:
      - label=needs-approval
    actions:
      review:
        type: APPROVE
        message: "LGTM"
        bot_account: "Pockriglian"

  - name: gated merge
    conditions:
      - label=do-merge
      - label=release
    actions:
      merge:
        merge_bot_account: "Pockriglian"
